- dashboards/helpers.go
- dashboards/prometheus/prometheus_overview.go
- dashboards/prometheus/prometheus_remote_write.go
- main.go
This pull request introduces a new feature for building a Prometheus Remote Write dashboard. The changes include creating a new file, importing necessary libraries, and defining a function to build the dashboard with specific panels and variables.
* **New File Created**: `dashboards/prometheus/prometheus_remote_write.go` to define the Prometheus Remote Write dashboard.
* **Function Definition**: `BuildPrometheusRemoteWrite` function to build the dashboard with specified panels and variables.
* **Imports**: Added necessary imports for building the dashboard using the Perses SDK and Prometheus query functionalities.
* **Variables**: Added cluster, instance, and URL variables for dynamic querying.
* **Panels**: Added panels for visualizing the highest timestamp and rate metrics.
> [CHORE] adding prometheus remote write dashboard

- internal/dashboards/node_exporter/node_exporter.go
- main.go
- pkg/panels/node_exporter/node_exporter.go
This pull request introduces a new feature for building and displaying node exporter dashboards. The changes include the addition of new functions for creating various panels and integrating them into the main dashboard builder.
* **Node Exporter Panels**:
* Added functions to create panels for CPU, Memory, Disk, and Network metrics (`internal/dashboards/node_exporter/node_exporter.go`).
* Implemented detailed panel configurations for each metric, such as CPU usage percentage, memory usage in bytes, and network received bytes (`pkg/panels/node_exporter/node_exporter.go`).
* **Main Dashboard Builder**:
* Integrated the new node exporter panels into the main dashboard builder function (`main.go`).
* Updated the import statements to include the new node exporter package (`main.go`).
> [FEATURE] adding node exporter nodes dashboard

- internal/dashboards/node_exporter/node_exporter_cluster_use_method.go
- main.go
- pkg/panels/node_exporter/node_exporter.go
This pull request introduces a new set of functionalities for building a Node Exporter dashboard using the USE method. The changes include the creation of new panel options for various metrics and the integration of these panels into the dashboard building process.
* [`internal/dashboards/node_exporter/node_exporter_cluster_use_method.go`](diffhunk://#diff-182fdde22b4b957efc20a917cf2b6854e8f966e8de4c965dd6facbaffd89d62dR1-R62): Added functions to create panel groups for CPU, Memory, Network, Disk IO, and Disk Space metrics using the USE method. These functions are used to build a comprehensive Node Exporter dashboard.
* [`main.go`](diffhunk://#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R52-R59): Integrated the new Node Exporter dashboard into the main application …
> [FEATURE] adding node exporter cluster use method

- internal/dashboards/node_exporter/node_exporter_cluster_use_method.go
This pull request to `internal/dashboards/node_exporter/node_exporter_cluster_use_method.go` includes changes to enhance the flexibility and accuracy of the node exporter cluster use method. The main updates involve adding an instance label matcher and modifying functions to accept both cluster and instance label matchers.
* Added imports for `labelValuesVar` and `listVar` to support new variable handling. (`internal/dashboards/node_exporter/node_exporter_cluster_use_method.go`)
* Modified `withClusterCPU`, `withClusterMemory`, `withClusterNetwork`, `withClusterDiskIO`, and `withClusterDiskSpace` functions to accept both `clusterLabelMatcher` and `instanceLabelMatcher` parameters. (`internal/dashboards/node_exporter/node_exporter_cluster_use_method.go`)
* Added a new instance label …
> [CHORE] adding instance filter node use method

- internal/dashboards/prometheus/prometheus_overview.go
This pull request includes a change to the `internal/dashboards/prometheus/prometheus_overview.go` file to improve the Prometheus overview by updating the label matchers.
Improvements to Prometheus overview:
* [`internal/dashboards/prometheus/prometheus_overview.go`](diffhunk://#diff-960368e6a9516163c22c4c51622863da5e22739d96d688992d663d00d1eee056L74-R75): Modified the `BuildPrometheusOverview` function to use the `prometheus_build_info` metric and added a new label matcher for the `job` label.
> [FIX] prometheus overview instance var not loading

- main.go
This pull request includes a small change to the `main.go` file. The change modifies the default value of the `cluster-label-name` flag to an empty string.
* [`main.go`](diffhunk://#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261L23-R23): Changed the default value of the `cluster-label-name` flag from `"cluster"` to an empty string.
> [CHORE] making cluster label default empty

- Makefile
- docker-compose.yaml
- examples/docker-compose.yaml
- examples/perses/config.yaml
- examples/perses/datasource.yaml
- examples/perses/project.yaml
This pull request introduces several changes to set up and manage a demo environment using Docker Compose, along with configuration files for the `perses` service. The most important changes include adding new demo-related commands to the `Makefile`, updating Docker Compose configurations, and adding new configuration and resource files for the `perses` service.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R5-R16): Added `demo` and `clean-demo` targets to set up and clean the demo environment using Docker Compose.
* [`examples/docker-compose.yaml`](diffhunk://#diff-34686806ce7369ba8aea6b65936d44d3fe45a2799ac680b4f12741adaa0eed2bR1-R12): Introduced a new Docker Compose configuration for the `perses` service, specifying the image, command, …
> [CHORE] adding demo env

- Makefile
- README.md
- examples/perses/project.yaml
This pull request includes several changes to improve the development workflow and documentation for the Perses Community Dashboards. The most important changes include updating the Makefile to rename a target, enhancing the README with detailed project information, and modifying the project configuration.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L7-R7): Renamed the `demo` target to `start-demo` to better reflect its purpose.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1-R23): Added detailed project information, including an overview of available dashboards, library panels, and instructions for local development.
* [`examples/perses/project.yaml`](diffhunk://#diff-2877fe0dc1e6029021 …
> [DOCS] adding readme

- examples/perses/datasource.yaml
- pkg/panels/alertmanager/alertmanager.go
- pkg/panels/node_exporter/node_exporter.go
- pkg/panels/prometheus/prometheus.go
This pull request includes several changes to improve the descriptions and formatting of panels in the `alertmanager` and `node_exporter` packages. The most important changes include updating URLs, adding detailed descriptions for Prometheus metrics, and refining query formats.
* Updated descriptions to specify the Prometheus metrics used and the data shown in various panels. [[1]](diffhunk://#diff-27c723a4f015acf2bd7ccb3dc051c81d42a2af63043a09dd2ea24b7f28bb52beR17-R19) [[2]](diffhunk://#diff-27c723a4f015acf2bd7ccb3dc051c81d42a2af63043a09dd2ea24b7f28bb52beL40-R56) [[3]](diffhunk://#diff-27c723a4f015acf2bd7ccb3dc051c81d42a2af63043a09dd2ea24b7f28bb52beR104-R111) [[4]](diffhunk://#diff-27c723a4f015acf2bd7ccb3dc051c81d42a2af63043a09dd2ea24b7f28bb52beR155-R164)
* Refined the series name …
> [REFACTORY] code consistency

- Makefile
- examples/dashboards/operator/alertmanager-overview.yaml
- examples/dashboards/operator/node-exporter-cluster-use-method.yaml
- examples/dashboards/operator/node-exporter-nodes.yaml
- examples/dashboards/operator/prometheus-overview.yaml
- examples/dashboards/operator/prometheus-remote-write.yaml
- examples/dashboards/perses/alertmanager-overview.yaml
- examples/dashboards/perses/node-exporter-cluster-use-method.yaml
- examples/dashboards/perses/node-exporter-nodes.yaml
- examples/dashboards/perses/prometheus-overview.yaml
- examples/dashboards/perses/prometheus-remote-write.yaml
This commit modifies Makefile to add generated dashboard YAML (both operator CRD and regular config) to examples dir.
Provides easy way for downstream user to just get YAML without cloning. Also, makes it easier to view dashboard diffs for future changes.
> Add generated dashboards to example dir

- pkg/dashboards/dashboard_writer.go
- pkg/dashboards/exec.go
This commit adds helper methods to exec and dashboardWriter to allow getting PersesDashboard structs (as runtime.Objects) directly instead of writing to file.
This is particularly useful when building controllers that deploy PersesDashboards.
> Add exec, dashboardWriter methods for getting runtime.Objects

- .gitignore
- Makefile
- pkg/dashboards/exec.go
This pull request updates the output directory paths for dashboard builds to align with a new directory structure. The changes affect both the `Makefile` and the `pkg/dashboards/exec.go` file.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L20-R21): Changed the `OUTPUT_DIR_OPERATOR` and `OUTPUT_DIR_PERSES` default paths from `./dist/dashboards/...` to `./built/dashboards/...` to reflect the new directory structure.
* [`pkg/dashboards/exec.go`](diffhunk://#diff-370ccb5720a3898eaf957f9613990a48911b3e25752e161d90d93171e0f9c6e5L26-R26): Updated the `output-dir` flag's default value from `./dist` to `./built` to ensure consistency with the updated directory structure.
> [CHORE] aligning output dir with percli dac build cmd

- examples/dashboards/operator/perses/perses-overview.yaml
- examples/dashboards/perses/perses/perses-overview.yaml
- pkg/dashboards/perses/perses_overview.go
- pkg/panels/perses/perses.go
* Introduced visual settings for time series panels, including:
- `display`: line
- `lineWidth`: 0.25
- `areaOpacity`: 0.5
- `palette`: auto mode
* Enhanced the overall appearance and readability of the dashboard metrics.
cc: @saswatamcode
Signed-off-by: Akshay Iyyadurai Balasundaram <akshay.iyyadurai.balasundaram@sap.com>
> ENHANCMENT(perses-dashboard): 🎨 Add visual configuration for time series panels in Perses

- examples/dashboards/operator/perses/perses-overview.yaml
- examples/dashboards/perses/perses/perses-overview.yaml
Follow up for https://github.com/perses/community-dashboards/pull/64
- ran `make build-dashboards`
@nicolastakashi: Do you think it makes sense to have a step in GitHub Actions PR workflow to check if the committer had executed `make build-dashboards` and if not, fail the workflow? 
Signed-off-by: Akshay Iyyadurai Balasundaram <akshay.iyyadurai.balasundaram@sap.com>
> Perses dashboard follow-up

- examples/dashboards/operator/kubernetes/controller-manager-overview.yaml
- examples/dashboards/perses/kubernetes/controller-manager-overview.yaml
- main.go
- pkg/dashboards/kubernetes/controller_manager/controller_manager.go
- pkg/dashboards/kubernetes/kubelet/kubelet.go
- pkg/panels/kubernetes/controller_manager.go
- pkg/panels/kubernetes/globals.go
This commit adds the kubernetes-mixin dashboard for controller manager.
Couldn't try on a local-cluster, but tried on an openshift one, and it works!
> Add dashboard for Kube Controller Manager

- examples/dashboards/operator/kubernetes/controller-manager-overview.yaml
- examples/dashboards/operator/kubernetes/kubelet-overview.yaml
- examples/dashboards/operator/perses/perses-overview.yaml
- examples/dashboards/operator/thanos/thanos-compact-overview.yaml
- examples/dashboards/operator/thanos/thanos-query-frontend-overview.yaml
- examples/dashboards/operator/thanos/thanos-query-overview.yaml
- examples/dashboards/operator/thanos/thanos-receive-overview.yaml
- examples/dashboards/operator/thanos/thanos-ruler-overview.yaml
- examples/dashboards/operator/thanos/thanos-store-overview.yaml
- examples/dashboards/perses/kubernetes/controller-manager-overview.yaml
- examples/dashboards/perses/kubernetes/kubelet-overview.yaml
- examples/dashboards/perses/perses/perses-overview.yaml
- examples/dashboards/perses/thanos/thanos-compact-overview.yaml
- examples/dashboards/perses/thanos/thanos-query-frontend-overview.yaml
- examples/dashboards/perses/thanos/thanos-query-overview.yaml
- examples/dashboards/perses/thanos/thanos-receive-overview.yaml
- examples/dashboards/perses/thanos/thanos-ruler-overview.yaml
- examples/dashboards/perses/thanos/thanos-store-overview.yaml
- pkg/dashboards/kubernetes/controller_manager/controller_manager.go
- pkg/dashboards/kubernetes/kubelet/kubelet.go
- pkg/dashboards/perses/perses_overview.go
- pkg/dashboards/thanos/common.go
- pkg/panels/gostats/gostats.go
- pkg/panels/kubernetes/kubelet.go
- pkg/panels/perses/perses.go
This commit brings the CPU usage panel into gostats, and uses the same in perses, kubelet, and thanos dashboards.
As the panel is based on client_golang process collector, it should fit a variety of use cases.
Also, adds a seriesNameToUse arg to gostats panels, as certain dashboards need to label by {{pod}} and others by {{instance}}.
> Unify CPU Usage into gostats

- examples/dashboards/operator/kubernetes/controller-manager-overview.yaml
- examples/dashboards/operator/kubernetes/kubelet-overview.yaml
- examples/dashboards/operator/perses/perses-overview.yaml
- examples/dashboards/operator/thanos/thanos-compact-overview.yaml
- examples/dashboards/operator/thanos/thanos-query-frontend-overview.yaml
- examples/dashboards/operator/thanos/thanos-query-overview.yaml
- examples/dashboards/operator/thanos/thanos-receive-overview.yaml
- examples/dashboards/operator/thanos/thanos-ruler-overview.yaml
- examples/dashboards/operator/thanos/thanos-store-overview.yaml
- examples/dashboards/perses/kubernetes/controller-manager-overview.yaml
- examples/dashboards/perses/kubernetes/kubelet-overview.yaml
- examples/dashboards/perses/perses/perses-overview.yaml
- examples/dashboards/perses/thanos/thanos-compact-overview.yaml
- examples/dashboards/perses/thanos/thanos-query-frontend-overview.yaml
- examples/dashboards/perses/thanos/thanos-query-overview.yaml
- examples/dashboards/perses/thanos/thanos-receive-overview.yaml
- examples/dashboards/perses/thanos/thanos-ruler-overview.yaml
- examples/dashboards/perses/thanos/thanos-store-overview.yaml
- pkg/panels/gostats/gostats.go
- pkg/panels/perses/perses.go
- pkg/panels/thanos/common.go
- pkg/panels/thanos/thanos_compact.go
- pkg/panels/thanos/thanos_query.go
- pkg/panels/thanos/thanos_query_frontend.go
- pkg/panels/thanos/thanos_receive.go
- pkg/panels/thanos/thanos_ruler.go
- pkg/panels/thanos/thanos_store.go
This commit fixes quantile panels for which metrics are nearly always in seconds unit.
> Fix units on seconds_ histogram metrics

- README.md
- examples/dashboards/json/operator/etcd/etcd-overview.json
- examples/dashboards/operator/etcd/etcd-overview.yaml
- examples/dashboards/perses/etcd/etcd-overview.yaml
- main.go
- pkg/dashboards/etcd/etcd.go
- pkg/panels/etcd/etcd.go
This commit ports over the etcd mixin from https://github.com/etcd-io/etcd/blob/main/contrib/mixin/mixin.libsonnet
In general this dashboard is mostly used with kubernetes, however as upstream is a separate mixin, let's keep it separate here.
There are some unrelated changes in the PR, but once we merge #81, those will go in, and I'll rebase.
> feat: Add etcd overview dashboard from etcd-mixin

- README.md
- examples/dashboards/json/operator/alertmanager/alertmanager-overview.json
- examples/dashboards/json/operator/blackbox-exporter/blackbox-overview.json
- examples/dashboards/operator/alertmanager/alertmanager-overview.yaml
- examples/dashboards/operator/blackbox-exporter/blackbox-overview.yaml
- examples/dashboards/perses/alertmanager/alertmanager-overview.yaml
- examples/dashboards/perses/blackbox-exporter/blackbox-overview.yaml
- pkg/dashboards/alertmanager/alertmanager_overview.go
- pkg/dashboards/blackbox/blackbox.go
- pkg/panels/alertmanager/alertmanager.go
- pkg/panels/blackbox/blackbox.go
Improve panel sizing for Blackbox and Alertmanager dashboards, also missing commit from previous pr https://github.com/perses/community-dashboards/pull/63
Some screenshots of the changes
> Fix: panel sizing - Blackbox and Alertmanager

- .github/workflows/checks.yaml
This pull request updates the GitHub Actions workflow to improve the linting process by separating concerns and adding a new job for dashboard validation. The most important changes include renaming an existing job for clarity and introducing a new job to validate dashboards using the Perses CLI.
* [`.github/workflows/checks.yaml`](diffhunk://#diff-4af11422a4987e947e5a47adead7a30d32cdb2db82e2d3fe36f8e6cbe84d5ac5L10-R10): Renamed the `check-golang` job from "Golang and UI Linting" to "Golang Linting" to better reflect its scope.
* [`.github/workflows/checks.yaml`](diffhunk://#diff-4af11422a4987e947e5a47adead7a30d32cdb2db82e2d3fe36f8e6cbe84d5ac5R31-R46): Added a new `check-dashboards` job to validate dashboards. This includes steps to build dashboards locally and validate them using the …
> [CI] adding dac lint

- .github/CODEOWNERS
This pull request updates the `.github/CODEOWNERS` file to assign ownership of all files to specific team members.
Ownership update:
* [`.github/CODEOWNERS`](diffhunk://#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R1): Added `@nicolastakashi`, `@saswatamcode`, and `@ibakshay` as code owners for all files in the repository.
> [CHORE] adding code owners
